/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#002109',
        'surface-dim': '#d6dae3',
        'secondary-container': '#fe545a',
        'on-primary-fixed-variant': '#92001c',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#5b000d',
        'error-container': '#ffdad6',
        outline: '#8f6f6e',
        primary: '#b7102a',
        'on-primary-container': '#fffbff',
        'on-surface': '#171c22',
        'primary-container': '#db313f',
        'inverse-primary': '#ffb3b1',
        background: '#f8f9ff',
        'on-secondary': '#ffffff',
        'outline-variant': '#e4bebc',
        'surface-variant': '#dee3eb',
        surface: '#f8f9ff',
        'on-surface-variant': '#5b403f',
        'secondary-fixed-dim': '#ffb3b0',
        'tertiary-container': '#00873c',
        'tertiary-fixed-dim': '#3de273',
        'inverse-surface': '#2c3137',
        'surface-bright': '#f8f9ff',
        'on-tertiary-fixed-variant': '#005322',
        secondary: '#b71f2d',
        'on-primary-fixed': '#410007',
        'surface-container-low': '#f0f4fc',
        'surface-container-high': '#e4e8f1',
        'inverse-on-surface': '#edf1f9',
        'on-secondary-fixed': '#410006',
        'surface-tint': '#bb152c',
        tertiary: '#006b2e',
        'primary-fixed': '#ffdad8',
        'on-secondary-fixed-variant': '#93001b',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#ffb3b1',
        'surface-container-highest': '#dee3eb',
        'secondary-fixed': '#ffdad8',
        'surface-container': '#eaeef7',
        'tertiary-fixed': '#66ff8e',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#f7fff3',
        'on-background': '#171c22',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        margin: '2rem',
        'space-md': '1rem',
        gutter: '1.5rem',
        'space-xl': '2.5rem',
        'gutter-mobile': '1rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'headline-lg-mobile': ['Chivo'],
        'display-hero-mobile': ['Chivo'],
        'headline-sm': ['Chivo'],
        'body-md': ['Work Sans'],
        'display-hero': ['Chivo'],
        'body-lg': ['Work Sans'],
        'label-md': ['Work Sans'],
        'label-lg': ['Chivo'],
        'headline-lg': ['Chivo'],
        'body-sm': ['Work Sans'],
        'headline-md': ['Chivo'],
        'label-tech': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '800' }],
        'display-hero-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '900' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '900' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '18px', fontWeight: '600' }],
        'label-lg': ['16px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.015em', fontWeight: '800' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-tech': ['12px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
